projects:
  app:
    name: 'Kong'
    schemaPath: './schema.graphql'
    extensions:
      endpoints:
        hub:
          url: 'https://kong.yearn.fi/api/gql'
          headers:
            'user-agent': 'JS GraphQL'
          introspect: false
